name: flutter_responsive_menu
description: Generate a responsive menu.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  badges: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: